# Conversation States

AMOUNT = 0
CATEGORY = 1
DESCRIPTION = 2
SPLIT = 3
EXACT_AMOUNT = 4
RATIO = 5
SETTLE_MENU = 6
PARTIAL_SETTLEMENT = 7
EDIT_SELECT_FIELD = 8
EDIT_NEW_VALUE = 9
RECEIPT_GROUP_SELECT = 10
RECEIPT_CONFIRM = 11
EQUAL_AMONG_SELECT = 12